### ISSUE TITLE
I lost 0.5 ether while transferring to my EtherDelta wallet

### ISSUE THREAD

**Issue by hqubaisi** [etherdelta/etherdelta.github.io#100]
hi, I sent 0.5 ether to my ether wallet in EtherDelta, first of all, it took forever, then once I saw the [transaction ](https://etherscan.io/tx/0xb9fa2317739971fec3cf9b6ba1ae645b54419886c7cd7377be8e7a0281993115) was completed, I noticed that it was [transferred ](https://etherscan.io/tx/0x3f6914e7ccb5427203d3afc52e0f64cb72b645840e0f69a422d130ab032bca26) to another wallet (I didn't do that), then [transferred](https://etherscan.io/tx/0x3c332aaafd5e8c1a431a7fd0883f00eeda9bb864b9c6a814c74ff1625e3761c6) from that wallet to yet another wallet again. So how can this be possible ? please assist.

**Comment by hqubaisi** [comment]
sorry to post the issue here, I couldn't find any support contact in the website

**Comment by zackcoburn** [comment]
Did you use the correct URL? Is your computer compromised?

**Comment by hqubaisi** [comment]
I used this : https://etherdelta.github.io, no it is not compromised, I do so many transaction with this PC

**Comment by zackcoburn** [comment]
Check your browser history.

**Comment by hqubaisi** [comment]
is this legitimate: https://etherdelta.com/ ?

**Comment by zackcoburn** [comment]
Yes. Do you have any others in there?

**Comment by hqubaisi** [comment]
no, only the ones I mentioned

**Comment by zackcoburn** [comment]
How did you create the wallet you use on EtherDelta? Where did you store
the private key?

**Comment by hqubaisi** [comment]
I created new account, and I copied both the address & key, paste it in a txt file, zipped it with password. after that, I send 0.5 ether directly. closed the browser. After few hours, I opened the txt file, using the address & key, I logged in back and found 0 ether. Next day I noticed the tracking that I mentioned in the first post here.

**Comment by cyberdak** [comment]
your address ? you can check it on etherscan.io see which tx got your 0.5
eth.

hqubaisi <notifications@github.com>于2017年9月11日周一 下午5:00写道：

**Comment by hqubaisi** [comment]
you can also noticed from this address [history](https://etherscan.io/address/0x57f46e95bffc302839ba97d0a48ff4d506b21d26) (this is the strange address that received the 0.5 ether first) it send some ethers to another address called **etherdelta_2**, how can this be possible, is this part of EtherDelta ??

**Comment by hqubaisi** [comment]
@cyberdak I already did and it is something I didnt

**Comment by zackcoburn** [comment]
Did you check for viruses/malware?

**Comment by hqubaisi** [comment]
I protected already, no viruses, no malwares..

**Comment by hqubaisi** [comment]
sorry but may I ask you a question, are you working for EtherDelta ?? if yes, tracing the transactions I already shared, does any of the addresses looks familiar ??

**Comment by hqubaisi** [comment]
@zackcoburn previous comment for you

**Comment by zackcoburn** [comment]
The 0x57f4 address that took your funds is not familiar to me.

**Comment by hqubaisi** [comment]
but if you see this address history, in some transactions, it was sending money to etherdelta_2 address !!!

https://cdn.pbrd.co/images/GJUHOsM.png

**Comment by zackcoburn** [comment]
etherdelta_2 is the EtherDelta smart contract. So he probably redeposited
your tokens and sold them.

**Comment by zackcoburn** [comment]
He sent your tokens back to EtherDelta to sell them. EtherDelta is
decentralized, so he controls the funds now.

**Comment by hqubaisi** [comment]
does your website store the addresses data ? if that the case then maybe your website was compromised, not me

**Comment by zackcoburn** [comment]
Your private key is stored in your browser. It is not stored on a server.
