### ISSUE TITLE
Request: release the source code for the web app

### ISSUE THREAD

**Issue by macbem** [etherdelta/etherdelta.github.io#118]
If I'm right, the only thing we can see now is the minified, 110k LOC monster file.

Why don't you open source your source code instead of just releasing the minified part? It'd probably make EtherDelta way more accessible for contributors etc.

**Comment by RogierVelde** [comment]
Second this, it'd boost confidence as well.

**Comment by UniBanker** [comment]
So is there just no source code for this available then?
