### ISSUE TITLE
How can I place new order via API? (poor documentation)

### ISSUE THREAD

**Issue by NovikovViktor** [etherdelta/etherdelta.github.io#141]
@zackcoburn
Hello, I am trying to use EtherDelta API and as I am new in cryptography and I faced with trouble that I can't/don't understand how order could be properly created via API.
Here is the list of my questions, please respond:
1)  what is `contractAddr: the EtherDelta smart contract address`? and where I can get this string? its unclear according to documentation. Is this some kind of predefined string?
2) `v, r, s` how these values should be got? should I simply create three strings via `sha256` method? I found [this gistfile ](https://gist.github.com/zackcoburn/9cec5336f1bbe9705e8230caa9d4bcc4), and there is a large complicated logic of generating these values ( I can't get it  at once). I am trying to 'translate' nodejs code to php and currently I am not sure that I am doing everything right, as I descended to usage of "low level" libraries such as [this one](https://github.com/Bit-Wasp/secp256k1-php). Could you please give me at least expanded description how I can get these values (but some code samples also might be useful)?

Best regards, Viktor.

**Comment by zackcoburn** [comment]
Sorry, I'm working on better documentation. For now, here's a gist:
https://gist.github.com/zackcoburn/c29cad5c18785d8308949cbcc26e4f23

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by NovikovViktor** [comment]
@zackcoburn clear, I will wait for updates.
