### ISSUE TITLE
Lost money trying buy tokens from big seller

### ISSUE THREAD

**Issue by geronemo** [etherdelta/etherdelta.github.io#156]
Hello guys. Yesterday I tried to buy 273 TNT from big selling order but after 2 hours transaction was failed. And looks like that I money (they deduct ethereum from my account which I wanted to pay). Here details. https://etherscan.io/tx/0xc8127d8ff304724aed408da0036cf8ff0ce137f71e96dd3b2fc6d4f17779374b

**Comment by zackcoburn** [comment]
This trade failed (someone traded it before you did), which means you only
paid the Ethereum gas fee (0.001 ETH).

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by geronemo** [comment]
Man I'm sure >50% that I lost not only gas. Is it possible to check transaction closely

**Comment by zackcoburn** [comment]
Transactions that get an error in Ethereum eat the gas and revert all state
changes, so there's not much else to check. It's possible you did another
trade?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by geronemo** [comment]
I forgot about this situation as you persuade me that If transaction failed I can lose only gas. And there was amount about 0.1 eth.
But today I noticed strange transaction
https://etherscan.io/address/0xc12ebaea18b002af9b30138a3b045495faf1377a#internaltx for value 0.099973653642800001 eth
If you click on the transaction you'll see that 
from my account 0xc12ebaea18b002af9b30138a3b045495faf1377a 
to contract https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819 (etherdelta_2)
And this contract function
Function: withdraw(uint256 amount)
MethodID: 0x2e1a7d4d
[0]:00000000000000000000000000000000000000000000000001632d822046eb81
Which should return 0.099973653642800001 eth to my account

But at my account https://etherscan.io/address/0xc12ebaea18b002af9b30138a3b045495faf1377a
I don't see any inputs for 0.099973653642800001 eth.

Good if I misunderstand something but what if such a big contractor as Etherdelta has bug ?

**Comment by zackcoburn** [comment]
Click on the "internal transactions" tab and you'll see the transfer:
https://etherscan.io/tx/0xe5d63b2dac67dde7265af054424aa204ec17c30a4e9bc6960c52e3301eb82f31#internal

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by geronemo** [comment]
I see. Thanks. Sorry for spending your time.
