### ISSUE TITLE
returnTicker returns exponential values

### ISSUE THREAD

**Issue by mjdillon** [etherdelta/etherdelta.github.io#177]
Some of the values that are returned by the returnTicker api function include a large negative exponent, while most other values are returned as normal numbers. 

Is this the desired behavior?

`"ETH_EZEC2":{"tokenAddr":"0xae4191a7eb25713ac90483ea75828ae8038f94dc","quoteVolume":1,"baseVolume":0,"last":1e-9,"percentChange":0,"bid":3.01e-7,"ask":0.000009}`

**Comment by mjdillon** [comment]
Also, nulls sometimes crop up:

`"ETH_TKR":{"tokenAddr":"0xb45a50545beeab73f38f31e5973768c421805e5e","quoteVolume":13336.816,"baseVolume":3.668,"last":null,"percentChange":null,"bid":0.000245,"ask":0.00024}`

**Comment by zackcoburn** [comment]
It's just the way JavaScript handles big or small numbers. Like if you open up nodejs and type 0.0000001, it will spit back 1e-7. You can then do something like (1e-7).toFixed(9) (what the UI does), for example.

As for `last` sometimes being null... I'll have to look into that. The logic for `last` is overcomplicated so it can report the 1 hour vwap unless there has been no trading in the last hour, and there might be an edge case there.

**Comment by mjdillon** [comment]
grumble... grumble... nodejs...
