### ISSUE TITLE
API doesn't work for `myTrades` and `myOrders`

### ISSUE THREAD

**Issue by adamsmd** [etherdelta/etherdelta.github.io#193]
[API.md](https://github.com/etherdelta/etherdelta.github.io/blob/master/docs/API.md) claims that the following URLs access a user's trades and orders.
```
https://api.etherdelta.com/myTrades/[USER ADDRESS]/[TOKEN ADDRESS]/[PAGE]
https://api.etherdelta.com/myOrders/[USER ADDRESS]/[TOKEN ADDRESS]/[PAGE]
```

However, I can't get them to work.  For example the following should get the `SALT` trades for my account, but it outputs nothing even though I can clearly see such trades when using the web page:
```
wget -q -O- https://api.etherdelta.com/myTrades/0xc297ce89eb439223c078dc3f8f89d886de014e52/0x4156d3342d5c385a87d264f90653733592000581/0
```

Am I doing something wrong?

**Comment by zackcoburn** [comment]
Try this URL:
https://cache.etherdelta.com/myTrades/0xc297ce89eb439223c078dc3f8f89d886de014e52/0x4156d3342d5c385a87d264f90653733592000581/0

It might be blank the first time you load it (caching mechanism).

Btw, the REST API is going to be deprecated soon in favor of a new socket
API (which the frontend is actually already using).

**Comment by adamsmd** [comment]
That works.  Thanks.  (Closing this issue.)
