### ISSUE TITLE
Can I already try new socket API?

### ISSUE THREAD

**Issue by jnst** [etherdelta/etherdelta.github.io#195]
and, Are there documents or sample code? `https://socket.etherdelta.com`

**Comment by zackcoburn** [comment]
Yes, the frontend is already using the socket API. Documentation/examples
will be available soon.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by jnst** [comment]
OK, I just wait.

Close.
