### ISSUE TITLE
Socket API: Add `tokenAddr` to trades in `market`

### ISSUE THREAD

**Issue by adamsmd** [etherdelta/etherdelta.github.io#198]
The JSON objects in a `trades` event are structured the same as the JSON objects in the `trades` part of a `market` event except that the `trades` event has a `tokenAddr` field but the `market` event does not.

For the client app I am developing to use the API, it would simplify things if they both contained the `tokenAddr` field and thus had the same structure as each other.

**Comment by adamsmd** [comment]
This also applies to the JSON objects in the `myTrades` part of a `market`.

**Comment by zackcoburn** [comment]
Done!

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by adamsmd** [comment]
Awesome!  It works great!
