### ISSUE TITLE
Sorry, why published the minified version?

### ISSUE THREAD

**Issue by agusputra** [etherdelta/etherdelta.github.io#202]
Sorry for my question.
I try to read the source code: https://github.com/etherdelta/etherdelta.github.io/tree/master/js but it is the minified version.

Why not published unminified version?

**Comment by zackcoburn** [comment]
Out of curiosity, do you have any guesses as to why?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by agusputra** [comment]
You want to use github pages or hosting. Or you want to use github issues for etherdelta. 
Is that true?

**Comment by zackcoburn** [comment]
My question is less "Why does EtherDelta use GitHub" and more "Why is the
code minified and partially closed-source."

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by agusputra** [comment]
You also want to use GitHub features but you also want EtherDelta become your proprietary software.

**Comment by zackcoburn** [comment]
Exactly. EtherDelta is proprietary.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by agusputra** [comment]
OK, Thanks for replying me.

**Comment by zackcoburn** [comment]
No problem!

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
@agusputra Could you close this issue since your question is answered? Thanks!

**Comment by chrisfranko** [comment]
oh what the fuck is the point then
