### ISSUE TITLE
Coinmarketcap price of ATMChain  for ETHDelta market way off

### ISSUE THREAD

**Issue by 7--** [etherdelta/etherdelta.github.io#204]
https://coinmarketcap.com/currencies/attention-token-of-media/#markets
Says $0.105694 actually about $0.3 

This call returns the correct data, So i think its on their side, but maybe theres another endpoint theyre calling?
https://api.etherdelta.com/returnTicker

**Comment by zackcoburn** [comment]
The API is currently reporting 0.000349174 ATM/ETH (the last reported price
is a 1 hour volume weighted average price -- ATM is trading all over the
place, so I think this reported price is correct).

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by 7--** [comment]
The price is really 0.000101000ATM/ETH  look at it https://etherdelta.com/#ATM-ETH

**Comment by zackcoburn** [comment]
I know, but the API reports a 1 hour VWAP so you can't manipulate the price
shown to coinmarketcap by trading a tiny amount at an extreme price. There
were some larger trades recently at 0.0006, bringing the vwap up.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by 7--** [comment]
Oh shit. I had no idea about that. Thank you very much

**Comment by MeoMix** [comment]
@7-- Would you mind closing this issue now that your concern has been addressed? Thanks!
