### ISSUE TITLE
New API connection limits

### ISSUE THREAD

**Issue by minibbjd** [etherdelta/etherdelta.github.io#216]
With the new websocket API, are there any limits? Like number of websocket session per IP, data fetched, etc?

**Comment by zackcoburn** [comment]
See "Rate limit" in the document -- 12 per minute.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by minibbjd** [comment]
I don't understand the rate limit per minute with a websocket connection. 

When I subscribe to a market, the new order book entries and trades get pushed over to me. I don't fetch myself, so there is nothing that I could throttle to 12 per minute. What am I missing?

**Comment by zackcoburn** [comment]
It only applied to requests you make ("getMarket" or "message"). Messages
that get pushed to you don't count.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by minibbjd** [comment]
Thanks for the explanation!
