### ISSUE TITLE
add coin  (BTCB) for : www.bitcoinblue.info

### ISSUE THREAD

**Issue by Bitcoin-Blue** [etherdelta/etherdelta.github.io#217]
name bitcoin blue
add coin erc20 (BTCB) for : www.bitcoinblue.info
Token Symbol= ETHDZ
Address: 0x848ae4cc01c97297cdb4465bc06b8bcdf27996ba
decimals : 0
https://etherdelta.com/#0x848ae4cc01c97297cdb4465bc06b8bcdf27996ba-ETH
Thank you

**Comment by Bitcoin-Blue** [comment]
Bitcoin Blue (BTCB)
The web site https://bitcoinblue.info/

wallet site https://bitcoinblue.info/wallet/

Total supply 36.000.000 (Like Bitcoin)

Name Bitcoin Blue
Symbool BTCB
Decimals 0

Contact

Website ( the website) : https://www.bitcoinblue.info/
Facebook https://www.facebook.com/Bitcoin-Blue-127278424700111/
Mail help@bitcoinblue.info
Telegram https://t.me/joinchat/B6ii1wzYNBJnmslRFGqcEA
 twitter  https://twitter.com/bitcoinblueBTCB

**Comment by Bruttagente** [comment]
LOL! Same symbol as #211 ?? How many tokens are you doing?

**Comment by MeoMix** [comment]
@zackcoburn Can you close this one as a duplicate? Thanks!
