### ISSUE TITLE
enhancement - add filter by textfield to coin index

### ISSUE THREAD

**Issue by johndpope** [etherdelta/etherdelta.github.io#218]
Use case - I'm looking for bitcoin cash - 
currently have to scroll through cooky slider
should be able to type BCH - and have it pre populate with answers

<img width="507" alt="screen shot 2017-10-29 at 4 51 28 am" src="https://user-images.githubusercontent.com/289994/32142011-f08c6f5e-bc64-11e7-84ab-0cf24d02fd42.png">

eg

<img width="457" alt="screen shot 2017-10-29 at 4 53 33 am" src="https://user-images.githubusercontent.com/289994/32142023-3d3b10f8-bc65-11e7-882f-702ca072b3a0.png">

**Comment by Bitcoin-Blue** [comment]
Bitcoin Blue (BTCB)
The web site https://bitcoinblue.info/

wallet site https://bitcoinblue.info/wallet/

Total supply 36.000.000 (Like Bitcoin)

Name Bitcoin Blue
Symbool BTCB
Decimals 0

Bitcoin Blue AIRDROP

https://docs.google.com/forms/d/e/1FAIpQLSduwCMkuiThvLkY2SRRj-2cVHn1TPf4utAlQalGBVAdoXPqhA/viewform

Contact

Website ( the website) : https://www.bitcoinblue.info/
Facebook https://www.facebook.com/Bitcoin-Blue-127278424700111/
Mail help@bitcoinblue.info
Telegram https://t.me/joinchat/B6ii1wzYNBJnmslRFGqcEA
 twitter  https://twitter.com/bitcoinblueBTCB
