### ISSUE TITLE
Trades executed against wrong orders

### ISSUE THREAD

**Issue by minibbjd** [etherdelta/etherdelta.github.io#220]
I see an intermittent problem when taking orders using the websocket API. A different order is used for the trade as referenced by my trade. Here's an example:

The order I referenced in this trade was:

`{ id: '49a2c4ccb9559c25e00705f678af13ceca9626471c4bc07aa52f6292307129a1_sell',
  date: 2017-10-29T16:58:19.336Z,
  price: BigNumber { s: 1, e: -3, c: [ 639990000000 ] },
  amountGet: BigNumber { s: 1, e: 17, c: [ 6399, 90000000000000 ] },
  amountGive: BigNumber { s: 1, e: 2, c: [ 100 ] },
  deleted: undefined,
  expires: 4462787,
  nonce: 937246932,
  tokenGet: '0x0000000000000000000000000000000000000000',
  tokenGive: '0x957c30ab0426e0c93cd8241e2c60392d08c6ac8e',
  user: '0x8eb796ca783c2496f8058227310446d58cfa1e79',
  r: '0x7d0b0f40c0000d6025bff46aecae10e01e83719eb3ae56a83b07bd2dbe109174',
  s: '0x7308a0c2f59c24a1acabe91dd6fd18fcaba7b772c470cf8dc82f5c78bd4a1fb1',
  v: 27,
  amount: 100,
  amountBase: 0.63999,
  availableVolume: 90,
  ethAvailableVolume: 90,
  availableVolumeBase: 575991000000000000,
  ethAvailableVolumeBase: 0.575991 }

Result txid: `0x6dbe786593c870b06a34363efe18762ae3411deecc33c5113fa6fd221826659e`

The trade I got was:
Transaction | Type | MOD | ETH | MOD/ETH
0x6dbe7865 | Buy | 26.000 | 0.171 | 0.006564000

https://etherscan.io/tx/0x6dbe786593c870b06a34363efe18762ae3411deecc33c5113fa6fd221826659e

I was expecting a trade price of 0.006399900, as in the referenced order, not 0.006564000.

Anyone has an idea what's going on here?

EDIT1: 

Another example from earlier today, also with MOD:

Transaction | Type | MOD | ETH | MOD/ETH
0x7e658ef4 | Buy | 9.000 | 0.064 | 0.007077778

https://etherscan.io/tx/0x7e658ef4500490027320a633fcb6a6d8ecd392ede1c5d1d4d128decfcb7504df

I don't have the referenced order any longer, but the expected trade price was more in the 0.0064 ball park. (Now looked at the tx and it was 0.00637).

**Comment by DeltaBalances** [comment]
Looks like MOD has  0 decimals precision. https://etherscan.io/token/0x957c30ab0426e0c93cd8241e2c60392d08c6ac8e

I think there is some rounding happening with fees and the likes.

**Comment by minibbjd** [comment]
You mean on the (API) server side?

**Comment by DeltaBalances** [comment]
Inside the solidity smart contract. The problem with 0 decimal tokens is that things get lost in rounding. Its been a while since I looked into it, but I've seen some annoyances come by. 
 If you need to pay 0.1 token as fee, it needs to either take 0 or 1. If there are other divisions happening in there those need to round as well.

If you have for example 1 MOD left in your account, you can't even sell them with a taker order, as you cannot afford the 1+ fee.
