### ISSUE TITLE
get coin info from address

### ISSUE THREAD

**Issue by trashCoder555** [etherdelta/etherdelta.github.io#222]
I got this as sell order.
How can i get info about what is that coin?
Name, symbol - something.

[{"id":"c584c765c1adce0720125aa0b68088bd5ed099da921f2f12bf03d6fc302678cd_sell","amount":"-200","price":"0.000247998","tokenGet":"0x0000000000000000000000000000000000000000","amountGet":"49599600000000000","tokenGive":"0x28c8d01ff633ea9cd8fc6a451d7457889e698de6","amountGive":"200","expires":"4461147","nonce":"3027080404","v":28,"r":"0x665a3738747486d0ae974514dcba7046773cb7a3c2e3cf4c26922581b3745d0f","s":"0x5e88d3f1c2d0f38a9780de4a3f3b6106ce3024cfe6426cd57ed0424a9e5b1ae2","user":"0xBF3FF66b9f477E3c6f3B8b2c6053e398A243e6c1","updated":"2017-10-29T10:26:38.910Z","availableVolume":"200","ethAvailableVolume":"200","availableVolumeBase":"49599600000000000","ethAvailableVolumeBase":"0.0495996","amountFilled":null}]}]}

**Comment by zackcoburn** [comment]
Look under "tokenGive" (or "tokenGet," if it's a buy order).

0x28c8d01ff633ea9cd8fc6a451d7457889e698de6

Go to https://etherscan.io/token/0x28c8d01ff633ea9cd8fc6a451d7457889e698de6

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.
