### ISSUE TITLE
Rewriting bot examples to use web3/ethutil libraries - what am I missing?

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#234]
Hey there,

I've been working on modernizing the bot examples and am using the latest web3 alpha. A few things changed, nothing huge.

I've got everything working, but I expected `createOrder` to simplify more. Here's what I've got:

```
    const types = ['address', 'address', 'uint256', 'address', 'uint256', 'uint256', 'uint256'];
    const unpacked = [contractAddr, tokenGet, amountGet, tokenGive, amountGive, expires, orderNonce];
    const originalData = this.web3.eth.abi.encodeParameters(types, unpacked);

    // Drop the '0x'
    let data = originalData.substring(2);
    // Drop 24 0's from the first three sections of the encoding.
    data = data.substring(24);
    // Drpop 24 0's after the first 40 characters.
    data = data.substring(0, 40) + data.substring(64);
    // Drop 24 0's after the first 144 characters
    data = data.substring(0, 144) + data.substring(168);

    const hash = sha256(Buffer.from(data, 'hex'));
    const msgHash = ethUtil.hashPersonalMessage(Buffer.from(hash, 'hex'));
    const ecsign = ethUtil.ecsign(msgHash, Buffer.from(user.pk, 'hex'));
```

This logic replaces the calls to pack/sign and all the supporting methods.

A couple of questions:

- Why does `encodeParameters` pad with 24 leading zeros on the first three hex segments? Is this an indicator that I've done something incorrect, or is it just a difference between your `pack` implementation and `encodeParameters`?

- I was thinking I should be able to use `ethereumjs-tx`, create a new `Tx` object with the necessary data, call `tx.sign()`, and then access `v`, `r`, and `s` from within there. This doesn't seem to workout though -- maybe because your server still expects `sha256` where supporting libraries are hoping to move to `sha3`? Or do you feel like this should work and I've just overlooked something?

Thanks!

**Comment by zackcoburn** [comment]
For the tightly packed encoding, you should be able to use
https://github.com/ethereumjs/ethereumjs-abi#solidity-tightly-packed-formats
.

Your hashPersonalMessage and ecsign code should work, but I'd be curious at
what point does it differ from the result given by the code here:
https://github.com/etherdelta/etherdelta.github.io/blob/master/bots/service.js#L448

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Thanks for the quick response.

I don't think there's anything wrong with the hashPersonalMessage/ecsign code. My first concern does seem to be explainable by using tighter packing. I'll play around with that.

The second point I had touched on was more to do with compatibility with Tx:

- https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L231 Here is `Tx.sign`

- https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L143 Here is `Tx.hash`. You can see in the comments that it is generating `sha3-256` hash using `ethutil.rlphash`

- https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L260 Here is `ethutil.rlphash` 

I thought I should be able to use similar code to that of `takeOrder` for signing: https://github.com/etherdelta/etherdelta.github.io/blob/master/bots/service.js#L319 but I generate different v/r/s values when signing this way.

It's entirely possible I've just gotten something crossed on my end, but, given the explicit use of `sha256`, I thought maybe your server was just expecting an older encryption style?

**Comment by MeoMix** [comment]
👍 I can confirm that using `soliditySHA256` works as expected. Note that this isn't available in the latest version of `web3`. It only offers sha3. So, I'm pulling in the `ethereumjs-abi` library to get access to the sha256 version.

It would be nice if you'd upgrade the server to be compatible with either for a while and then deprecate 256, but I'm sure you're busy -- as we all are. :)

**Comment by MeoMix** [comment]
For those Googling in the future... here you go:

```
    const types = ['address', 'address', 'uint256', 'address', 'uint256', 'uint256', 'uint256'];
    const unpacked = [contractAddr, tokenGet, amountGet, tokenGive, amountGive, expires, orderNonce];
    const hash = ethAbi.soliditySHA256(types, unpacked);
    const msgHash = ethUtil.hashPersonalMessage(hash);
    const ecsign = ethUtil.ecsign(msgHash, user.pk);
```
