### ISSUE TITLE
Two issues (URI scheme and order function)

### ISSUE THREAD

**Issue by bitcoinmeetups** [etherdelta/etherdelta.github.io#235]
Hello. I have a website called bitcoinmeetups.org. I recently created a token called BMT. https://etherdelta.com/#0x699091dc769e30325deb3007574dac451e8ac806-ETH This should be the URL. There are two issues: a) sometimes the URI scheme redirects to etherdelta.com#BMT-ETH which is another token (typically after refreshing). This is a bug and a serious one because users could accidentally buy the wrong token. Also b) I cannot place any buy and sell orders.

Bmeet
![20171105153429](https://user-images.githubusercontent.com/2834754/32413228-b89210b4-c23f-11e7-95e6-18962bfdbe57.png)

**Comment by bitcoinmeetups** [comment]
![20171105154625](https://user-images.githubusercontent.com/2834754/32413262-86233008-c240-11e7-9771-9865cf3b135e.png)

**Comment by bitcoinmeetups** [comment]
@yusha1439 and devs

**Comment by bitcoinmeetups** [comment]
![20171105154625](https://user-images.githubusercontent.com/2834754/32413285-019c64e8-c241-11e7-8c5f-f2f3996a59d1.png)

**Comment by zackcoburn** [comment]
Fixed, thanks!

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

On Sun, Nov 5, 2017 at 8:50 AM, bitcoinmeetups.org <notifications@github.com

**Comment by bitcoinmeetups** [comment]
@zackcoburn That is tres cool how fast you fixed these bugs! Lovin' it.
