### ISSUE TITLE
Can't figure out trying to connect to API

### ISSUE THREAD

**Issue by zubairkahmed** [etherdelta/etherdelta.github.io#238]
Hey,

Can you maybe create a walkthrough video on how to connect to Websocket API and get data? I used to work with the older API and it was understandable than this one. I've killed 3 days trying to understand what to do to connect and get data. I even tried looking at those bots you've created but couldn't understand anything.

Other than the CEO of Etherdelta, anybody who has it figured out please do help.

Thank you!

**Comment by azeemkafridi** [comment]
+

Please consider this @zackcoburn

**Comment by dj2ball** [comment]
The documentation of how the SocketIO protocol is pretty much all you need to get started - once you connect you can thene manipulate the incoming data stream as per whatever language you are programming in...

**Comment by zubairkahmed** [comment]
@dj2ball I'm coding in Node Js and Socket.IO. Tried creating own server and passed data between client and server but doesn't get how to connect to API or get data from it. Can you help?

**Comment by MeoMix** [comment]
Just chiming in here that I think the current examples are totally sufficient. They're leagues beyond what most exchanges will offer you as getting started material. There's literally working bots that just need algorithms dropped into them and a little sprucing up.

I would encourage you to brush up on your dev skills a bit if you're finding this a major barrier to entry. It would seem... reckless to teach yourself to code while playing with real money.

Not sure that this issue has any real purposes or discussion to it and suggest @zackcoburn closes it.
