### ISSUE TITLE
Bad Instruction?  Missing OPcode

### ISSUE THREAD

**Issue by ethernoob** [etherdelta/etherdelta.github.io#242]
Hi,

 I am trying to take existing order through the API/smart contract
  I am wondering if you can check what's wrong with this transaction:
0x4de3ab9badc6570787fc07d2485e8e1d9480448e38cb661d41e28a525c665581

DebugTrace left at Missing OPcode, but I have no idea where to look for the problem.  The input data seems to show up correctly in the transaction log.

Thanks!

**Comment by ethernoob** [comment]
Thanks Zack for the quick response.
I went through the list of potential issues you mentioned, and it did turn out to be one bad parameter.
Everything is working now, thanks!

In the future, will there be plans to make the error messages more detailed?

**Comment by zackcoburn** [comment]
It's mostly a matter of Ethereum not providing good error handling (if a
transaction throws an error, all you know is that it threw an error, and
it's not easy to figure out why).

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.
