### ISSUE TITLE
Yo! Let's talk testing.

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#243]
Hey again,

So, after burning an obscene amount of gas due to failed testing on mainnet, I decided I'm broke enough to try and develop my bot in a proper testing environment. Hooray best practices. Boo multi-thousand dollar learning experiences.

Anyway, here's what I've got::

- Ropsten account, faucet filled with some ETH.
- Snagged the address for 1ST and ED contract from your JSON
- Confirmed I can pull in data from Ropsten network (`getAccountBalance`) is working OK

I don't have:

- The ability to place orders on test ED.

If I go to https://etherdelta.com/?config=testnet#1ST-ETH I can see my faucet ETH appearing, the page partially loads, but fails to fully load due to socket connection issues.

Error in dev console reads:

Refused to connect to 'ws://67.205.144.103:8002/socket.io/?EIO=3&transport=websocket' because it violates the following Content Security Policy directive: "connect-src 'self' localhost:8545 cache.etherdelta.com wss://socket.etherdelta.com etherscan.io api.etherscan.io syndication.twitter.com etherchain.org".

Questions:

- Am I SOL for using your server?
- If so, suggestions? Seems like building my own off-chain orderbook managing websocket is a bit... overkill... for testing.
- If not, what should I be doing? It looks like its a CORS issue, but it's unclear to me why you'd have CORS setup on a test server if you're making the test website publicly available, eh? I can probably fake the headers on my side to look like etherchain, but again, seems overkill.

EDIT:

- ! http://67.205.144.103:8002 actually loads an EtherDelta website. Maybe I should be interacting with that instead?

**Comment by zackcoburn** [comment]
Oh, the testnet API is currently not running.

What are you trying to test exactly? If you've been wasting gas, it sounds
like you've been trying to trade existing orders and failing. Either you've
just gotten quite unlucky and people keep "beating you to the punch," or
you're not sending the proper trade transaction. Can you send some example
failures?

**Comment by MeoMix** [comment]
Hey,

Aw. Bummer. Any ETA on when it might be back up?

I am trying to perform full integration testing against testnet. I would like to place orders, take another account's orders, and cancel my own orders. I'm struggling with:

- Having a non-zero balance for anything other than ETH. ETH faucet was easy, but alt coin faucets are harder.

- Acquiring the testnet order book from ED. I don't believe there's an on-chain way to see what orders are currently existing, right?

- Placing orders to the testnet ED. The docs did say that there was a way to do this on-chain, and perhaps I'll try that, but I'd prefer not modifying my code just to support a testing environment. Sorta defeats the purpose.

I definitely was not sending the proper transaction. My bot had an error with its math for calculating a scaling `gasPrice` based off of the estimated profit for taking a given transaction. I moved a bunch of ETH from the on-exchange wallet to off-exchange, thought that was 'safe enough', but awoke 50 ETH poorer as it repeatedly issued bad transactions.. compounded by the fact that throwing in solidity maxes out the gas usage. Heh. Check out the devastation here: https://etherscan.io/txs?a=0xe43351Bd6cdf6Cb64b1DfDe1464E98a0c403B631&p=2

Anyway, not trying to make this a pity party. Just acknowledging that I was being super fucking lazy with my testing environment, paid a heavy price for it, and am now trying to do better, but finding that things might be broken as you appear to be WIP on your new EtherDelta layout?

**Comment by djskinner** [comment]
I'm also interesting in developing against testnet beforing going live.

Did you have any luck finding a way to get some alt coins on testnet? I saw this (https://www.reddit.com/r/ethereum/comments/6i7twg/is_there_a_easy_and_fast_way_of_getting_some/) but suspect the token is not added to the ED contract so wont be of much use for testing purposes.

**Comment by MeoMix** [comment]
ED can trade any ERC20 token. It doesn't specifically have to be added to the exchange, afaik. I haven't gone through with this yet -- but yes either getting an alt coin, or minting your own coin and issuing yourself some, would be a good starting spot.

**Comment by yangbod123** [comment]
Have you done with testnet of ED? I want to test my smart contract interacting with ED too. But live net is too expensive for a test. Hope to hear from you soon.

**Comment by lexwodo** [comment]
Is there any progress in ED/testnet? Just tried web ui with ?config=testnet and python api calls (from bots example) and I found there is not way to place orders on testnet. I've used BOKKY and my own test ERC20 tokens.
