### ISSUE TITLE
Unable to get transaction count

### ISSUE THREAD

**Issue by BryGuy72** [etherdelta/etherdelta.github.io#247]
I have been playing with your taker.js bot example. I have installed all the dependencies that I see such as socket.io-client, web3, js-sha256, ethereumjs-util, ethereumjs-tx, etc.

I have had no issues pulling the orderbook data but when calling service.takeOrder(user, order, fraction) it bombs out. In service.js, when trying to getNextNonce, nothing is ever returned from this call:

self.web3.eth.getTransactionCount(user.addr, (err, result) =>

https://github.com/etherdelta/etherdelta.github.io/blob/633a048edc1e16dd41a3c3dd780b8963aa2b1870/bots/service.js#L274

The err handling in line 275 from the return of the promise is never reached:

https://github.com/etherdelta/etherdelta.github.io/blob/633a048edc1e16dd41a3c3dd780b8963aa2b1870/bots/service.js#L275

When following through the called stack, in web3.httpprovider, the payload is generated and trying to call eth_getTransactionCount. See here for object info from the debugger in this instance:

![image](https://user-images.githubusercontent.com/25085117/32569386-fa04cd1a-c48e-11e7-848b-7676d11b3024.png)

I am having issues isolating the exact line of code that is failing since no error seems to be raised and I am wading through the debugger while async hooks are firing.

When .then((nonce) subsequently fails, at line 282, the code just stops executing and no error info or any data from the promise is available for troubleshooting.

https://github.com/etherdelta/etherdelta.github.io/blob/633a048edc1e16dd41a3c3dd780b8963aa2b1870/bots/service.js#L282

Any help would be greatly appreciated!

**Comment by zackcoburn** [comment]
Which version of web3 do you have installed? Currently it depends on the
alpha one (which uses callbacks instead of promises).

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by BryGuy72** [comment]
Ahhhh, I'm running the latest, 1.0.0-beta.24.

Will try to roll it back and give it a whirl. Thanks.

**Comment by BryGuy72** [comment]
So is the best option Release 0.19.0?
https://github.com/ethereum/web3.js/releases?after=v1.0.0-beta.9

**Comment by BryGuy72** [comment]
I installed 0.19.0 and that resolved the issue.

New error is:

"Error: Invalid number of arguments to Solidity function"

Heading out the door for a few minutes but will try to track down that error next. If you have any suggestions before I sift through the debugger, I'm all ears. Thanks.

**Comment by MeoMix** [comment]
@BryGuy72 It's really not too bad to get everything upgraded to the latest beta version of web3. Plus, then you'd have current docs to work with.

For your specific issue, I don't think the problem is with the method you're calling. I believe it's with how you're setting everything up.

A few things:

- If you're using Infura for access to a BlockChain then make sure to create your own dev account rather than re-using the examples.

- Contracts no longer expect the `.at` method to be called. For instance: `self.web3.eth.contract(ABIEtherDelta).at(config.addressEtherDelta);` becomes `new self.web3.eth.contract(ABIEtherDelta, config.addressEtherDelta);`

I'm not aware of what your last issue is, but can probably help you out if you can narrow it down a bit.

**Comment by zackcoburn** [comment]
And if you do decide to downgrade to the version in package.json,
it's 0.17.0-alpha. Not that downgrading is ever the right idea. :)​

**Comment by BryGuy72** [comment]
@zackcoburn yes, I see that 0.17.0 is in the package.json but that wasn't an official release apparently. Yes, downgrading is rarely good, was just trying to get it up and running and then improve.

![image](https://user-images.githubusercontent.com/25085117/32585488-addef3c4-c4cb-11e7-9a0d-99b19e880d02.png)

@MeoMix thanks for your insight. This is actually my first time doing any blockchain-related development so I will probably be picking your brain if you don't mind. Although it had nothing to do with my issue, I took your advice and picked up an Infura account. Will work to eventually tweak as needed to support the latest version of web 3, but meanwhile, I figured out what was causing the "Error: Invalid number of arguments to Solidity function".

Frozeman must have changed things between 0.17 and 0.19 of web3. The three BigNumber amount-based arguments are getting stripped during the filter check since they are objects...

![image](https://user-images.githubusercontent.com/25085117/32585423-664a397e-c4cb-11e7-8464-ff8ceb65b659.png)

**Comment by MeoMix** [comment]
@BryGuy72 It's mine, as well. We're on an adventure together. :)

Hrm. I have not experienced the issue you're describing. I would except the BigNumbers to be converted to strings when serializing stuff. Can you paste some more code so I can see where exactly you're stuck?

**Comment by BryGuy72** [comment]
@MeoMix, indeed an adventure!

This was added in 0.19.0 post Zack's build against 0.17.0 so that's why. It surely changed again by the latest beta, See here:

![image](https://user-images.githubusercontent.com/25085117/32586000-4b34d6a0-c4ce-11e7-8392-be0071704343.png)

https://github.com/ethereum/web3.js/commit/89b9cb9e046edf22ecac706f5d5983c6d764f84d#diff-583d79234b227141b5bbe753af385722

Let me tweak a little and I might be hitting you back up for more help if I get stuck!

**Comment by MeoMix** [comment]
I am currently using:
    "web3": "^1.0.0-beta.24"

and don't have any troubles.

**Comment by BryGuy72** [comment]
Cool. My latest error when performing elf.web3.eth.sendRawTransaction() is:

insufficient funds for gas * price + value

Seems to be a common issue for others when performing eth transactions. As if it's a catch-all error and not accurate. I know I have plenty of eth for gas available for this low quantity with a low gas price.

Debugging is a nightmare due to async structure. Will dig into this more tomorrow.

**Comment by zackcoburn** [comment]
Make sure you specifically have enough ETH left for gas in your Wallet, as
opposed to on deposit in the EtherDelta smart contract.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by BryGuy72** [comment]
Thanks, but plenty of ETH in my wallet.

**Comment by zackcoburn** [comment]
Hmm. I haven't seen a case before where that error is wrong about what it
means. What gasPrice and gasLimit are you using?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by BryGuy72** [comment]
I tried as low as
  gasLimit: 1500000,
  gasPrice: 10000000,

**Comment by zackcoburn** [comment]
That's a pretty big gas limit of 1.5M. Together those imply only 0.015 ETH,
but that is a pretty expensive gas fee.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by BryGuy72** [comment]
@zackcoburn @MeoMix in playing with trying to reinstall the latest version of web3 I encountered a ton of errors even after clearing the npm cache. Eventually I realized that the web3 installation was failing at certain points since I am running it on a Windows server. I set the appropriate flags and now have the latest web3 again. 

@MeoMix, I see that now web3 is now split across what appears to be 17 packages lol. Will have to see which ones, if all, are needed.

**Comment by BryGuy72** [comment]
Temperamental Windows installer installed all but the main web3 package lol. Finally cleaned that up and see that I should be able to just reference the main web3 package as before....

**Comment by BryGuy72** [comment]
Making progress with rewriting, but still running into some issues when altering the code to support the 1.0.0-beta.24 version of web3.

@MeoMix can I hit you up on gitter.im or somewhere else to pick your brain a little?

**Comment by MeoMix** [comment]
I hang out in Discords all day, feel free to come say hi. This is just a test room that I test a Discord bot I'm writing in: https://discord.gg/XXEsZf
