### ISSUE TITLE
service.js printOrderbook() is showing incorrect spread

### ISSUE THREAD

**Issue by BryGuy72** [etherdelta/etherdelta.github.io#248]
Hey Zack, awesome project. You've done some really great work on ED! 

Looks like you are doing this solo and don't have any other contributors. I just noticed a very small bug and thought I'd let you know. The spread calculation is inaccurate here:

https://github.com/etherdelta/etherdelta.github.io/blob/633a048edc1e16dd41a3c3dd780b8963aa2b1870/bots/service.js#L228

Since you first reversed the sells here for the purpose of orderbook printing from top down:

https://github.com/etherdelta/etherdelta.github.io/blob/a69b1646daab68812a37d6541d8d6f7c7eb983af/bots/service.js#L222

When you reference [0], it means the spread is using the 10th best sell instead of the best for the purpose of calculating the spread.

I know it's minor, but just thought I'd let you know!

**Comment by zackcoburn** [comment]
Fixed!

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
@BryGuy72 Can you please close this issue once you feel it's sufficiently resolved?
