### ISSUE TITLE
API: Missing fields in "market" messages

### ISSUE THREAD

**Issue by adamsmd** [etherdelta/etherdelta.github.io#255]
Using the new API I am sporadicly getting "market" messages that don't have "returnTicker", "myOrders", "myTrades", or "myFunds" fields.  They contain only "order" and "trade" fields.

This happens only occasionally, and I can make my client work around this but am reporting this in case it indicates an upstream bug.

**Comment by zackcoburn** [comment]
Yeah, this is normal. If the data isn't immediately available, it skips
that part. In the example service.js, it deals with this by repeatedly
calling "getMarket" until all the data is there.
