### ISSUE TITLE
Should the order book resort itself after a partial trade?

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#256]
Hey there,

While working on your code and comparing it to my implementation I noticed that your order book sorts by an order's original quantity. If it is partially filled, and its remaining quantity drops, it doesn't resort itself in the order book. I thought this was a bit odd as there's no visual indicator for original quantity. So, it can look like the order book is just out of place. Plus, I think it makes more sense to sort when remaining quantity changes.

Thoughts?

**Comment by zackcoburn** [comment]
That's a good point. That's a bug, and I'll fix it. :)​

**Comment by MeoMix** [comment]
Yay! >:D Told you I am getting in deep into this. Onward!
