### ISSUE TITLE
Unable to receive filtered data

### ISSUE THREAD

**Issue by CineTek** [etherdelta/etherdelta.github.io#266]
Hello,

I feel like I am doing something terribly wrong here. Currently trying to get my data through a C# client by providing the websocket with my ETH address:

          JObject jout = JObject.FromObject(new { user = "my eth address" }); 
          socket.Emit("getMarket", jout);
                
   Edit(This all happens in the "connect" event)        

I do get a 'market' response but all it shows are the "returnTicker" and empty trades/orders.

There are also listeners for "myOrders" and "myTrades" events just in case they are necessary but they do not return anything.

The "trades" events properly returns all trades happening

I have EtherDelta open with the same account where I can see that my account is currently active in the system.

![image](https://user-images.githubusercontent.com/3392549/32902800-abada0cc-caf3-11e7-82ca-bbabc47caddc.png)

**Comment by zackcoburn** [comment]
The market response will have missing data if it's not immediately
available. waitForMarket in the example service.js is an example of calling
it again until the data is available.

Zack

**Comment by CineTek** [comment]
Thanks this explains a lot, I missed this step when examining the js examples!
