### ISSUE TITLE
Frequent socket disconnections even with ping request/pong response activity.

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#269]
Heya,

I noted another issue highlighting a concern I'm seeing. I thought it would be fair to bring it up as a separate problem because that issue seemed to have gone silent.

I am using the latest Socket.IO Client. `"socket.io-client": "^2.0.4",` I am establishing a socket connection to the EtherDelta server via:

```js
      socket: io(`https://socket.etherdelta.com`, {
        transports: ['websocket']
      })
```

I output logs for all the events which occur on the socket, but I'm not running it in verbose mode. I'll do so later today. I see ping/pong activity:

> info 12:41:51:366:      Pong! Latency: 126
> info 12:42:16:366:      Ping?
> info 12:42:16:475:      Pong! Latency: 109
> info 12:42:41:475:      Ping?
> info 12:42:41:565:      Pong! Latency: 90
> info 12:42:42:486:      Ping?
> error 12:43:03:517:     !! Disconnected from EtherDelta server
> info 12:43:04:779:      Attempting reconnection
> info 12:43:04:779:      Reconnecting. Attempt: 1
> info 12:43:06:385:      Reconnected
> info 12:43:06:386:      Connected to EtherDelta
> info 12:43:31:386:      Ping?
> info 12:43:31:491:      Pong! Latency: 105

I let my code run overnight and I note many disconnections. They do not seem to have any obvious timing patterns:

> error 11:20:55:413:     !! Disconnected from EtherDelta server
> error 11:38:00:431:     !! Disconnected from EtherDelta server
> error 11:45:35:220:     !! Disconnected from EtherDelta server
> error 11:54:39:101:     !! Disconnected from EtherDelta server
> error 12:05:54:069:     !! Disconnected from EtherDelta server
> error 12:13:16:006:     !! Disconnected from EtherDelta server
> error 12:21:24:292:     !! Disconnected from EtherDelta server
> error 12:26:02:437:     !! Disconnected from EtherDelta server

My code is not currently taking any action against the smart contract or EtherDelta server. So, if it were to be timing out due to inactivity, I would expect there to be a consistent interval between these disconnections. Instead, we see that the timings are: 17 minutes, 7.5 minutes, 9 minutes, 11 minutes, 7.5 minutes, 8 minutes, 4.5 minutes, etc..

I would say that 95% of the time I am able to reconnect immediately on the first try. Sometimes, it takes me two tries and I receive `websocket error` as the reason for failure to connect.

I know you said you have no idea why this is happening and that it "shouldn't," but, it is, and I would like to know if you have any intention of working with developers to resolve the issue.

**Additionally**, it would be helpful if nonces could be included with market updates. If I request market information, and am receiving order updates, it is challenging to know if updates for orders have come in before I receive the market information. I need to patch new order information into the market update, but have no way of knowing which orders to patch in. Thoughts?

For reference, here's my output log from last night for errors:

> error 10:53:17:146: !! Disconnected from EtherDelta server
> error 10:59:33:440: !! Disconnected from EtherDelta server
> error 11:03:53:760: !! Disconnected from EtherDelta server
> error 11:15:37:556: !! Disconnected from EtherDelta server
> error 11:46:29:420: !! Disconnected from EtherDelta server
> error 11:51:30:091: !! Disconnected from EtherDelta server
> error 12:30:43:848: !! Disconnected from EtherDelta server
> error 12:35:53:183: !! Disconnected from EtherDelta server
> error 12:45:15:974: !! Disconnected from EtherDelta server
> error 01:00:11:413: !! Disconnected from EtherDelta server
> error 01:04:24:748: !! Disconnected from EtherDelta server
> error 01:15:32:618: !! Disconnected from EtherDelta server
> error 01:20:43:790: !! Disconnected from EtherDelta server
> error 01:35:25:761: !! Disconnected from EtherDelta server
> error 01:55:57:828: !! Disconnected from EtherDelta server
> error 01:56:55:643: !! Disconnected from EtherDelta server
> error 02:18:05:159: !! Disconnected from EtherDelta server
> error 02:19:04:163: !! Disconnected from EtherDelta server
> error 02:22:17:541: !! Disconnected from EtherDelta server
> error 02:41:59:262: !! Disconnected from EtherDelta server
> error 02:59:50:732: !! Disconnected from EtherDelta server
> error 03:00:42:000: !! Disconnected from EtherDelta server
> error 03:53:49:740: !! Disconnected from EtherDelta server
> error 04:14:13:136: !! Disconnected from EtherDelta server
> error 04:17:39:556: !! Disconnected from EtherDelta server
> error 04:18:16:325: !! Disconnected from EtherDelta server
> error 04:44:47:727: !! Disconnected from EtherDelta server
> error 04:50:05:575: !! Disconnected from EtherDelta server
> error 04:54:58:583: !! Disconnected from EtherDelta server
> error 05:02:21:504: !! Disconnected from EtherDelta server
> error 05:03:34:936: !! Disconnected from EtherDelta server
> error 05:04:28:900: !! Disconnected from EtherDelta server
> error 05:19:16:591: !! Disconnected from EtherDelta server
> error 05:30:51:483: !! Disconnected from EtherDelta server
> error 05:34:01:109: !! Disconnected from EtherDelta server
> error 05:35:48:710: !! Disconnected from EtherDelta server
> error 05:36:05:745: !! Disconnected from EtherDelta server
> error 05:37:06:258: !! Disconnected from EtherDelta server
> error 05:53:39:108: !! Disconnected from EtherDelta server
> error 06:00:02:646: !! Disconnected from EtherDelta server
> error 06:05:17:346: !! Disconnected from EtherDelta server
> error 06:07:01:697: !! Disconnected from EtherDelta server
> error 06:19:15:238: !! Disconnected from EtherDelta server
> error 06:19:34:510: !! Disconnected from EtherDelta server
> error 06:19:35:544: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 06:19:35:545: Failed to reconnect. Reason: Error: websocket error
> error 06:22:10:336: !! Disconnected from EtherDelta server
> error 06:25:23:292: !! Disconnected from EtherDelta server
> error 06:26:49:938: !! Disconnected from EtherDelta server
> error 06:40:05:398: !! Disconnected from EtherDelta server
> error 06:46:47:850: !! Disconnected from EtherDelta server
> error 06:52:52:560: !! Disconnected from EtherDelta server
> error 06:54:29:371: !! Disconnected from EtherDelta server
> error 06:56:28:522: !! Disconnected from EtherDelta server
> error 07:03:36:341: !! Disconnected from EtherDelta server
> error 07:10:31:395: !! Disconnected from EtherDelta server
> error 07:25:03:076: !! Disconnected from EtherDelta server
> error 07:26:31:530: !! Disconnected from EtherDelta server
> error 07:34:51:455: !! Disconnected from EtherDelta server
> error 07:35:58:070: !! Disconnected from EtherDelta server
> error 07:42:27:706: !! Disconnected from EtherDelta server
> error 07:54:12:855: !! Disconnected from EtherDelta server
> error 08:06:56:092: !! Disconnected from EtherDelta server
> error 08:07:55:051: !! Disconnected from EtherDelta server
> error 08:26:48:336: !! Disconnected from EtherDelta server
> error 08:31:04:386: !! Disconnected from EtherDelta server
> error 08:37:31:876: !! Disconnected from EtherDelta server
> error 08:46:04:329: !! Disconnected from EtherDelta server
> error 08:52:58:278: !! Disconnected from EtherDelta server
> error 08:52:59:161: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 08:52:59:162: Failed to reconnect. Reason: Error: websocket error
> error 08:54:28:989: !! Disconnected from EtherDelta server
> error 09:04:13:466: !! Disconnected from EtherDelta server
> error 09:04:15:446: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 09:04:15:447: Failed to reconnect. Reason: Error: websocket error
> error 09:07:32:393: !! Disconnected from EtherDelta server
> error 09:09:49:964: !! Disconnected from EtherDelta server
> error 09:27:04:005: !! Disconnected from EtherDelta server
> error 09:43:48:921: !! Disconnected from EtherDelta server
> error 09:44:08:874: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 09:44:08:875: Failed to reconnect. Reason: Error: websocket error
> error 09:44:25:774: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 09:44:25:776: Failed to reconnect. Reason: Error: websocket error
> error 09:50:48:612: !! Disconnected from EtherDelta server
> error 09:51:31:678: !! Disconnected from EtherDelta server
> error 10:00:48:823: !! Disconnected from EtherDelta server
> error 10:00:51:184: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 10:00:51:185: Failed to reconnect. Reason: Error: websocket error
> error 10:04:38:617: !! Disconnected from EtherDelta server
> error 10:09:45:121: !! Disconnected from EtherDelta server
> error 10:19:58:973: !! Disconnected from EtherDelta server
> error 10:20:19:637: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 10:20:19:641: Failed to reconnect. Reason: Error: websocket error
> error 10:20:19:653: Failed to connect to EtherDelta. Connection timed out.
> error 10:20:25:424: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 10:20:25:440: Failed to reconnect. Reason: Error: websocket error
> error 10:25:42:908: !! Disconnected from EtherDelta server
> error 10:38:18:451: !! Disconnected from EtherDelta server
> error 10:43:44:371: !! Disconnected from EtherDelta server
> error 10:44:22:223: !! Disconnected from EtherDelta server
> error 10:55:56:719: !! Disconnected from EtherDelta server
> error 11:18:46:369: !! Disconnected from EtherDelta server
> error 11:20:55:414: !! Disconnected from EtherDelta server
> error 11:38:00:434: !! Disconnected from EtherDelta server
> error 11:45:35:221: !! Disconnected from EtherDelta server
> error 11:54:39:102: !! Disconnected from EtherDelta server
> error 12:05:54:070: !! Disconnected from EtherDelta server
> error 12:13:16:007: !! Disconnected from EtherDelta server
> error 12:21:24:292: !! Disconnected from EtherDelta server
> error 12:26:02:440: !! Disconnected from EtherDelta server
> error 12:43:03:520: !! Disconnected from EtherDelta server
> error 12:53:59:505: !! Disconnected from EtherDelta server
> error 12:57:49:563: !! Disconnected from EtherDelta server
> error 01:05:04:075: !! Disconnected from EtherDelta server
> error 01:05:04:808: Failed to connect to EtherDelta. Reason: Error: websocket error
> error 01:05:04:814: Failed to reconnect. Reason: Error: websocket error
> error 01:05:29:507: !! Disconnected from EtherDelta server
> error 01:09:37:673: !! Disconnected from EtherDelta server

**Comment by zackcoburn** [comment]
Interesting. There's definitely something odd going on here, but I'm not
sure what yet.

**Comment by dj2ball** [comment]
I noticed the same thing, I wonder if it has anything to do with the socket client's ability to reconnect gracefully without specific instructions? I set the parameter "forceNew: true" in the connection options and have been getting much better results.

**Comment by zackcoburn** [comment]
Interesting. I'll look into adding that.

**Comment by MeoMix** [comment]
@zackcoburn Any updates?

**Comment by dj2ball** [comment]
Between this issue and the orders emits seeming to randomly stop, I'm finding it very difficult to work with the Socket in a meaningful way at the moment. Hopefully @zackcoburn has some luck in trying to pin down what is going on
