### ISSUE TITLE
HI,ZACK

### ISSUE THREAD

**Issue by hccdev** [etherdelta/etherdelta.github.io#273]
@zackcoburn How to make a token listed on ETHERDELTA?  Should we pay a fee or any issue should be dealed with?

**Comment by zackcoburn** [comment]
PM @etherdeltazack_twitter on
https://gitter.im/etherdelta/etherdelta.github.io

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
@hccdev Can you please close this issue now that it's been addressed?

**Comment by Imranfarid212** [comment]
Can someone please help me out on this. I'm dont find these token on my EtherDelta wallet anymore, please guide me through. 
![etherchain](https://user-images.githubusercontent.com/11363956/37447163-0a57bf44-27de-11e8-84e4-9463de962818.JPG)
![forkdelta balance](https://user-images.githubusercontent.com/11363956/37447172-11db43da-27de-11e8-8ff5-2710cc1d2c65.JPG)

**Comment by hccdev** [comment]
ok

**Comment by hccdev** [comment]
ok thx
