### ISSUE TITLE
Increasing the number of orders per user per side per token

### ISSUE THREAD

**Issue by reverendus** [etherdelta/etherdelta.github.io#274]
Trying to do any serious market making with 5 orders per side limitation is difficult. Message `Too many orders already. You can only have 5 per side per token.` appears too often.

I suggest raising this limit to at least 10 orders per side. I don't think it will make it much easier to spam EtherDelta with orders, but will definitely make life easier to everybody who want to integrate with you.

**Comment by zackcoburn** [comment]
Yes, I think it's time to increase this to 10. It will be updated the next
time there's a new batch of tokens (probably tonight).

**Comment by MeoMix** [comment]
@zackcoburn Did this happen in one of the latest updates, or is it still pending?

**Comment by zackcoburn** [comment]
This has been done.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
@zackcoburn Great, thanks. I don't suppose you release patch notes with your updates? :)

@reverendus Could you please close this issue now that it's been resolved?

**Comment by reverendus** [comment]
Closing. Thanks @zackcoburn
