### ISSUE TITLE
Valid amount for taking orders

### ISSUE THREAD

**Issue by JihyeHong** [etherdelta/etherdelta.github.io#278]
Hello, 
I am testing the bot example for Node.js.
From the given example, I am getting an error message by calling 'testTrading' function, which is "Order will fail".

taker.js
```
const desiredAmountBase = 0.001;
const fraction = Math.min(desiredAmountBase / order.ethAvailableVolumeBase, 1);
```

service.js
```
self.takeOrder = (user, order, fraction) => new Promise((resolve, reject) => {
    self.getNextNonce(user)
    .then((nonce) => {
      const amount = order.amountGet.times(new BigNumber(String(fraction)));
```

So I modified with the amount constant as 0.05 like below then the transaction succeed but I got 0.0 coin from this transaction although it was successful.

service.js line 283
```
const amount = 0.05;
```

This is the transaction information. 
https://etherscan.io/tx/0x7a0162059ff5621637bc4fa5ccb51e367a7f73f730bcfbf3b033a0a158bcd74e

Please let me know how I can provide a valid amount to take orders.

Thank you.

**Comment by zackcoburn** [comment]
In trader.js, the desiredAmountBase is the amount you want to buy of the
given order, specified in terms of the ETH you will use to buy the token.
For example, if the best sell order is for 10 tokens at a price of 0.123
(implying all 10 tokens would cost 1.23 ETH), and desiredAmountBase is
0.01, you'd be buying 0.01 ETH worth of tokens, or 0.0813 tokens. Hopefully
that example explains what the trader.js is doing. Let me know if you have
further questions.

**Comment by JihyeHong** [comment]
Thanks for your answer Zack,
Now I definitely understand how it works. 
So I only need to change the desiredAmountBase value in taker.js as I understand without modifying service.js. 
But still, it gives me 'Order will fail' message. 

taker.js debug log
```
Balance (ED, ETH): 0.000
Balance (wallet, token): 0.000
Balance (ED, token): 0.000
Best available: Sell 250.000 @ 0.021600000
desiredAmountBase: 0.01
fraction: 0.0018518518518518517
```

service.js debug log
```
tokenGet: 0x0000000000000000000000000000000000000000
amountGet: 5400000000000000000
tokenGive: 0xd26114cd6ee289accf82350c8d8487fedb8a0c07
amountGive: 250000000000000000000
expires: 4601078
nonce: 811167443
user: 0x1f22b9a1346ff129c014e4601e06155f5a47ec88
v: 27
r: 0xfe1701d655f11d06847bf3a87df57c79efce78c22464ce85ebc175b7c4a8b8f3
s: 0x588a0ee59fc512e52b72e74c11a800d1f81653f2113a377afc0c67a229fe41ec
amount: 9999999999999999.18
user addr: 0xEFabB6B3444a055A401A45bc78a0bDdD7649bcCA
Order will fail
```

Would you have a look what's wrong with these input data? 

Many thanks.

**Comment by zackcoburn** [comment]
The issue here is that your user address,
0xEFabB6B3444a055A401A45bc78a0bDdD7649bcCA,
doesn't have any ETH deposited into the EtherDelta smart contract.

**Comment by JihyeHong** [comment]
Aha! perfect!
As you expected, I only had balance in my wallet, not in the smart contract. 
Thank you so much 👍
