### ISSUE TITLE
Is it possible to have a correct, client-side representation of the order book within a minute of start-up?

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#279]
Hey there,

I was doing some musing and realized why I see some odd behavior on EtherDelta. It got me thinking.

You cache market data on a 60 second interval, but orders are pushed live. If I start-up my code and get cached market information... then that information is missing, on average, all orders for the last 30 seconds, no?

You see this more readily through the EtherDelta GUI. A trade will be on the order book, you refresh the page, and the trade disappears from the order book. This is because we've lost some information we *just* had because all we have is an older cache now.

I feel like this would also explain why I sometimes see multiple updates of the same info from your socket -- as if it were necessary to rebroadcast info several times to ensure everyone had all the info at *some point* in the future.

Is this all correct? Thoughts on what to do about it?

**Comment by zackcoburn** [comment]
The "within a minute of startup" part might be difficult, but you could
have your script start listening for orders, then do "getMarket" after 60
seconds, and then apply all the stored orders against the getMarket result,
to ensure 100% accuracy. Admittedly, this is something you shouldn't have
to think about... it's also on the todo list to remove this cache at some
point.

**Comment by MeoMix** [comment]
Hey it's totally fine. I'm not bashing - shit's hard to build 100% perfect the first time. Just trying to make sure my data is matching your data in scenarios where it seems like it might be wrong. :)

And yes, that is a possible way to do it. Other exchanges use nonces to achieve this. Request data, capture orders, then replay order data until nonces are synchronized. I'm you're aware though!

Thanks for the response
