### ISSUE TITLE
Odd behavior when trying to use 100% of my balance to take a Buy order.

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#281]
Hey there,

I have some alt coin (lets say RHOC) and I have 8 of it (represented to 8 decimal places). I try to take a BUY order and use my entire balance, 800000000. I'm seeing this transaction fail

If I reduce the amount being sent by .003 - it succeeds.

I don't seem to be having the same issue when taking SELL orders...

This would lead me to believe that fees are being taken out of the RHOC I am selling rather than an equivalent ETH amount from my off-contract wallet.

Is this true, or am I connecting unrelated ideas? I haven't tested smaller fractional amounts yet, but this issue seems a little odd. I've been careful to test with round number values to avoid any issues with decimal precision.

**Comment by zackcoburn** [comment]
If you're selling tokens, fees are paid in the token (from your
"EtherDelta" deposit). If you're buying tokens, fees are paid in ETH (from
your "EtherDelta" wallet). Just a bit of a quirk.

**Comment by MeoMix** [comment]
Fuuuuuuuuuuuuuu.

Yup. That's it. Okay, cool. MY BOT RUNS! I thought I had a precision rounding error with BigNumber shit for a while there but eventually put 2 and 2 together on that quirk. :)

**Comment by dj2ball** [comment]
Just wanted to thank you for this issue, I spent like 6 hours last night thinking something odd was happening and it was the same issue you were having MeoMix - so glad I found this!
