### ISSUE TITLE
socket.on('orders') no long working

### ISSUE THREAD

**Issue by djskinner** [etherdelta/etherdelta.github.io#282]
Hi,

I couple of days ago I had a little script working that would call 'marketData' for a token and then would receive order updates when 'orders' was emitted on the socket. I'm trying it today and 'orders' is never emitted. Has something changed with the API?

Cheers!

**Comment by zackcoburn** [comment]
Hmm, I'm definitely getting 'orders' and 'trades' events when I connect to
the socket through service.js.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by djskinner** [comment]
Me too now, again, with the same code. Perhaps there were some connectivity issues when I had the issue.

Thanks for getting back to me so quickly.
