### ISSUE TITLE
What's the purpose of knowing the "decimals" for a coin?

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#295]
Hey there,

I am working on adding functionality to my bot. I am hoping to have it dynamically grow into new markets/tokens as they're added to EtherDelta.

Currently, I copy/paste the list of tokens from your configuration JSON file. I do this because it has all the information I think I need - contract address, symbol name, and decimal places.

I don't fully understand why decimal places is a necessary field. I believe that EtherDelta can trade against any ERC20 coin. It doesn't have to be officially supported by EtherDelta.

Given this... how could knowing the decimal places of a coin be required for proper functionality? It would seem like it isn't, and it's strictly for display purposes when rounding values. It doesn't actually impact math.

Is this true? If not, why not?

**Comment by zackcoburn** [comment]
Correct, it's only for display purposes. If you think of a token amount as
something like "1 followed by 18 zeros because the number of decimals is
18," then you don't even need to worry about decimals at all.

**Comment by MeoMix** [comment]
@zackcoburn Thanks for the quick reply, as always. Let me know if I can help at all with debugging your server issues. I'm here to help! :)

**Comment by GoldRat** [comment]
> it's only for display purposes.

Is it? How to calculate amount in base units for [message (order)](https://github.com/etherdelta/etherdelta.github.io/blob/master/site/docs/API.md#message-order) then?
