### ISSUE TITLE
Order executed still showing in order book

### ISSUE THREAD

**Issue by gabriel-dehan** [etherdelta/etherdelta.github.io#296]
Hello, just started using etherdelta and one of my orders is executed (quote has been credited, base has been debited) but my order is still in the order book.

Also I can't cancel it because I have an insufficient balance for this transaction but it feels weird for me to pay a cancelation fee (the transaction cost ?) for an order that has been already executed.

Also, the trade doesn't show in my trade history. I can provide screenshot if needed or any non-compromising information that you might require. 

Is this normal (maybe there is a few hours of lags or something, I'll check tomorrow) ?

Cheers

**Comment by zackcoburn** [comment]
Check back later. The event scanner isn't working for some reason, so
you're not seeing your recent trade. Looking into it.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by gabriel-dehan** [comment]
Thanks it has been resolved, closing the issue :)
