### ISSUE TITLE
VERI LOST IN SPACE

### ISSUE THREAD

**Issue by Dagger1** [etherdelta/etherdelta.github.io#297]
I attempted to exchange some VERI this morning and it seems to have disappeared along with some ETH. Transaction  0xfe0786eb381f9dc28a90689ae4a315c4fddfda836f07eeb7747ce7d37b220bbc
Can someone please help?

**Comment by zackcoburn** [comment]
This is a deposit. Your VERI is in your "EtherDelta" column. I checked this
on
https://deltabalances.github.io/#0x0eca929e3ea5e08b579f5aa11aeea0393697e4d6

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by Dagger1** [comment]
Thanks so much Zack! Why does it not appear here? https://etherscan.io/address/0x0eca929e3ea5e08b579f5aa11aeea0393697e4d6 

----- Original Message -----

**Comment by zackcoburn** [comment]
Etherscan doesn't show the amount you have deposited to the EtherDelta
smart contract. In order to see what you have on deposit, you have to use
either EtherDelta or DeltaBalances.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by Dagger1** [comment]
Thanks again Zack! Much learning to do. Can you please recommend a website or video that would help me better learn/navigate EtherDelta?

**Comment by zackcoburn** [comment]
> **EtherDelta guides**
> You should read the guides. They go over the details of getting started
with an account, depositing, withdrawing, trading, etc.
>
https://www.reddit.com/r/EtherDelta/comments/6hrxjw/etherdelta_guides_for_first_time_users/
> Remember, don't click any EtherDelta links from unknown sources. Always
go to the official URL: https://etherdelta.com. Bookmark that and always
use the bookmark.
> There are also a number of user-created videos on YouTube that you may
find useful. In particular, Crypt0's video is particularly good:
https://www.youtube.com/watch?v=PzpeEuPMsL8


Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by Dagger1** [comment]
Excellent! I have read through the guides, but visuals really help. Here's a screen shot of EtherDelta page....it seems to be stuck. The address is https://etherdelta.com/#VERI-ETH but stuck on PPT and I get nothing under "Trades", "Orders" and "Funds". Not sure what to do.
![image](https://user-images.githubusercontent.com/34096645/33409773-241efb1c-d54b-11e7-8e17-291de2defbd5.png)

Thanks so much for all your help...much appreciated!

**Comment by zackcoburn** [comment]
Try Chrome instead of FireFox. It usually works better with EtherDelta.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by Dagger1** [comment]
Will Do! Thanks again!

**Comment by Dagger1** [comment]
Will Do! Thanks again!

**Comment by Dagger1** [comment]
Hi Zack, 


I'm still having the same issue with EtherDelta website in Chrome as I am with Firefox. When I type in https://etherdelta.com, it automatically goes to https://etherdelta.com/#PPT-ETH. I choose VERI and it stays on PPT. I get nothing under "Trades", "Orders" and "Funds". Below is another screen shot. Any other ideas? 








----- Original Message -----

**Comment by zackcoburn** [comment]
Hmm, I'm not sure. Can you come over to
https://gitter.im/etherdelta/etherdelta.github.io for live support? If
nobody responds, you can PM me (@etherdeltazack_twitter).

**Comment by Dagger1** [comment]
Sure....I'll give it a shot. 


Thanks! 

----- Original Message -----

**Comment by Dagger1** [comment]
Hi Zack. I did what you suggested below and I did get some suggestions, like, clear cache, history, etc., refresh, restart, which I had already tried without success. I still appears whenever I import my ether wallet, it gets stuck on loading. Any help would be greatly appreciated. 

Thanks, 
Dagger1 

----- Original Message -----

**Comment by zackcoburn** [comment]
Maybe try installing MetaMask for Chrome and import your account into
MetaMask.

On Dec 2, 2017 5:42 PM, "Dagger1" <notifications@github.com> wrote:

Hi Zack. I did what you suggested below and I did get some suggestions,
like, clear cache, history, etc., refresh, restart, which I had already
tried without success. I still appears whenever I import my ether wallet,
it gets stuck on loading. Any help would be greatly appreciated.

Thanks,
Dagger1

----- Original Message -----

**Comment by Dagger1** [comment]
I was thinking about trying that....I'll give it a shot. Thanks! 

----- Original Message -----

**Comment by Dagger1** [comment]
Hi Zack, 

Is there any other way to move my VERI and ETH from EtherDelta back to my wallet without using EtherDelta? It appears many on the live chat having the same loading issue that I am. 

Thanks, 
Dagger1 

----- Original Message -----

**Comment by zackcoburn** [comment]
Does the balance panel (upper left) load for you?

**Comment by Dagger1** [comment]
No...here's a screen shot of what it looks like. 



----- Original Message -----

**Comment by Dagger1** [comment]
Zack, I checked and I did send the screen shot with the previous email. Not sure why you didn't see it. No balance showing up...appears to be loading. Any suggestions for solutions? 
----- Original Message -----

**Comment by zackcoburn** [comment]
I think GitHub is eating the screenshots. Maybe send an imgur link? Do you just see the ???

Did you try installing MetaMask and importing your private key into that?

**Comment by Dagger1** [comment]
Yes, "???" is what I get. I haven't tried MetaMask yet, as I saw others on live chat having the same loading issue. I'll try it soon and let you know the results. 

----- Original Message -----

**Comment by Dagger1** [comment]
Hi Zack, I did try MetaMask, balanced appeared this time. I initiated a withdraw of VERI to my wallet last night with no success. I had the Gas set at 4.. Perhaps I should up the gas? 

Thanks, 
Dagger1 

----- Original Message -----

**Comment by zackcoburn** [comment]
Yeah the ethereum network is overloaded with over 20,000 pending
transactions right now, so 4 gwei is pretty low.

**Comment by Dagger1** [comment]
Shall up the gas to 10 and retry the withdraw, or give it more time? 

----- Original Message -----

**Comment by zackcoburn** [comment]
This is all pending transaction sorted by gas price. You'd want to be on
page one or two there to get into the next block:
https://etherscan.io/txsPending?sort=gasprice&order=desc

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.
