### ISSUE TITLE
How to derive `availableVolume` from `ethAvailableVolume` ?

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#298]
Heya,

So, I'm changing up my logic so that decimal formatting will only be handled in the presentation layer. I am working on the assumption I do not have "decimals" for a given token.

A buy order from your server has these properties:

```
availableVolume:"255205"
availableVolumeBase:"1066756900000000000"
ethAvailableVolume:"2552.05"
ethAvailableVolumeBase:"1.0667569"
```

I understand that `ethAvailableVolumeBase` is the amount remaining in this order -- represented in the base token (ETH) as Ether. `availableVolumeBase` is similar, but is Ether converted to Wei.

The other two values represent the alt token being traded.

`ethAvailableVolume` is the amount remaining in this order -- represented as the alt token as Ether.

Therefore, I think that `availableVolume` is the alt token represented in Wei... but it isn't represented as 2552050000000000000000.  Given this -- how am I able to infer where the decimal place is for converting 255205 to 2552.05?

If this isn't possible, then how should I be interacting with the smart contract's `availableVolume` method? It returns a value such as `255205`.

Perhaps it is as simple as always adding the decimal place after two digits?

**Comment by zackcoburn** [comment]
This seems to be a token with 2 decimal places, which I calculated using
log10(255205/2552.05).​

**Comment by MeoMix** [comment]
@zackcoburn That's true, but doesn't answer my question. Let me try to rephrase?

I am trading against an unknown coin. So, just the contract address and no known decimals. I query the smart contract's `availableVolume` method. It returns a value such as `255205`

How am I to use this number?

If I call `availableVolume` with a sell order then `tokenGet` is Ethereum, `availableVolume` is clearly in wei, and I am able to convert wei to Ether by implicitly knowing that Ether is 1 with 18 0's.

It doesn't seem like there is a parallel with a buy order. I can't assume `availableVolume` is wei as `255205` -> `2552.05` is a shift of 2 decimal places not 18, yea?

**Comment by zackcoburn** [comment]
Oh, you mean if you don't have ethAvailableVolume to look at? In that case,
I guess you just don't know what that number really represents. At that
point you'd have to query the token's "decimals" function (which almost
every token included -- one notable exception is DGD).

**Comment by MeoMix** [comment]
I do -- just trying to make sure I'm not missing something since I was able to get away without knowing the decimal in every other spot in my code for now. :) Thanks for the reply!

**Comment by GoldRat** [comment]
> At that point you'd have to query the token's "decimals" function (which almost every token included -- one notable exception is DGD).

How to query it through API?
