### ISSUE TITLE
Socket pushes bad data

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/etherdelta.github.io#302]
Heya,

I received this in an `orders` update event:

![image](https://user-images.githubusercontent.com/1380995/33509693-aba2b13c-d6b8-11e7-9d68-01d686c62409.png)

`availableVolume` and `availableVolumeBase` are "undefined" strings. `ethAvailableVolume` and `ethAvailableVolumeBase` are NaN.

Not sure if you were aware of this possibility.

Cheers

**Comment by zackcoburn** [comment]
Can you paste the "id" here?

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
I've only got that partial id shown in the screenshot for now, but I put in some logging around the area to capture future order ids if it crops up again. Sorry about that.

**Comment by MeoMix** [comment]
@zackcoburn Got one.

2855738b9486864a39e7ddde4acf4effc1a5c3ee07947b2a5e280096e28e96b0_sell

**Comment by MeoMix** [comment]
b5cf5e3c3ea49ee08038904e5ce94b7e8b9e46616206ca6f192fa5daf1e78a09_buy

**Comment by MeoMix** [comment]
9718c45a89f10fc9afed6a8aff4bb091b09bbb11444c69269f62fa8ad82a9364_buy
