### ISSUE TITLE
off-chain order book and on-chain user balances

### ISSUE THREAD

**Issue by RomanBrodetski** [etherdelta/etherdelta.github.io#313]
Hi,
As far as I understand, the order book is capable of checking the user balance on-chain, so it's impossible to create an order of value higher than user has deposited.
What happens if user creates an order, and then withdraws the funds? I see two options:
* the order still shows up in the UI, and when someone tries to counterpart it, the ethereum transaction fails
* the off-chain order-book is capable of catching such an event and the order is invalidated as soon as there is not enough funds

**Comment by zackcoburn** [comment]
Off-chain order book catches that and removes the order (although if the
user re-deposits, the order comes back). As the person who created such an
order, you can cancel "underfunded" orders under the "Orders" tab under "My
transactions."
