### ISSUE TITLE
Ether not depositing!

### ISSUE THREAD

**Issue by bullbear1000** [etherdelta/etherdelta.github.io#314]
Hi can someone please help.. all I am trying to do is to deposit eth to etherdelta and it is failing every time. Never had it this bad. It's saying there was an error and I need to check I have enough ethereum in wallet to pay gas fee, which I do. It is just not allowing me to deposit eth, so I cannot purchase any tokens. Please tell me what do I need to do? Thanks

**Comment by zackcoburn** [comment]
What gas price are you using? According to https://ethgasstation.info/, the
safe low gas price is 44 gwei right now.

**Comment by bullbear1000** [comment]
No worries sorted it thanks, put gwei to 50. very expensive though!
