### ISSUE TITLE
Can't take any trade on DRGN token

### ISSUE THREAD

**Issue by cryptouser332** [etherdelta/etherdelta.github.io#317]
I've been trying to trade the DRGN-ETH pair on ED, but after 1 day of waiting I can't purchase any token yet. When I try to resend my order, ED warns me about that order already being taken, but not updating in the order book. Is there a way to cancel my transaction and making sure it will go through?

Thanks!

**Comment by zackcoburn** [comment]
There's no way to cancel a pending transaction, but you can replace it. I
tested the DRGN-ETH order book, and the top level order is not taken. Are
you using MetaMask? Are you on mainnet? What's your eth address?

**Comment by cryptouser332** [comment]
Hi @zackcoburn 

Never mind, I set GAS price to 60 GWEI and all trades went through. Though can't understand why the default price is set too low.

Thanks for your help Zack
