### ISSUE TITLE
Show an "Metamask not found" error

### ISSUE THREAD

**Issue by nivida** [etherdelta/etherdelta.github.io#333]
I would recommend you to show an error msg when Metamask is not installed or activated.

**Comment by zackcoburn** [comment]
It's possible to use EtherDelta without MetaMask.​

**Comment by nivida** [comment]
Okay i was wondering about the error with code 5.. and then i realized that i do not have metamask "installed". Maybe is this error because of an other Issue.

**Comment by zackcoburn** [comment]
The code 5 error is because you don't have a Ledger Nano S connected (this
is optional).

**Comment by nivida** [comment]
Okay but etherdelta is not loading. Newest Chrome on macOS Sierra. I will later post here an screenshot actualy @work

**Comment by zackcoburn** [comment]
Try clearing your cache and refreshing.
