### ISSUE TITLE
How to make a GET request to the API?

### ISSUE THREAD

**Issue by drhectapus** [etherdelta/etherdelta.github.io#338]
I'm querying the old API.

`https://api.etherdelta.com/returnTicker` works

But I want to use `https://api.etherdelta.com/trades/[TOKEN ADDRESS]/[PAGE]`

So I put in the contract address for CRED which is 0x8d12A197cB00D4747a1fe03395095ce2A5CC6819 as follows:

`https://api.etherdelta.com/trades/0x8d12A197cB00D4747a1fe03395095ce2A5CC6819/0`

And it's returning nothing? Am I using the wrong token address? A bit confused how to query this API here

**Comment by zackcoburn** [comment]
That address isn't CRED's address, it's the EtherDelta smart contract's
address.

**Comment by drhectapus** [comment]
That would explain it. How do I get the token's address then?

**Comment by zackcoburn** [comment]
You can look it up from the "Tokens" menu on Etherscan.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by drhectapus** [comment]
Working perfectly now. Thank you!
