### ISSUE TITLE
Balance not updated

### ISSUE THREAD

**Issue by vietdpham** [etherdelta/etherdelta.github.io#383]
Hi,
I import my MEW wallet to Etherdelta and deposit all I have to EtherDelta. But then I want to withdraw, it said I dont have enough gas. Then I deposit some 0.1 ETH to my MEW wallet, but this balance is not reflected in Etherdelta and I still cant withdraw.
How can I withdraw eth to MEW now?
Thanks.

**Comment by vietdpham** [comment]
fixed it

**Comment by sj77777** [comment]
Hi there,

How did you fix it?

 Cheers
