### ISSUE TITLE
Metamask to ED contract transfer is successfull but amount is not reflecting 

### ISSUE THREAD

**Issue by chetan-pandit** [etherdelta/etherdelta.github.io#392]
Txn Hash - 0x16ab2a9d26afd19807f5362d3f24921405b652d2fd60fa98c8e2e280b972fc8c

Please help

**Comment by chetan-pandit** [comment]
It was used by some pending transaction (those i could not cancel). Very poor interface :(

**Comment by Govind13100** [comment]
Hello, I have run the setup of your and also i have developed my own smart contract as your, so i have connected it to the setup of your clone. Everything is working fine like deposit , withdraw, transfer buy and sell but the " Order Book ", " Trade & Volume " and " Your transactions  " is not working, can you please help me out to get this data's.

When i look into your code file : main.6cfdd60c6d0446e78031.js , it inlcuding react code and rendering for ex Myorder.js , but i don't understand where it is coming from, it will be very great if you could help me out here. Thanks in advance
