### ISSUE TITLE
Did not place order because available volume too low.

### ISSUE THREAD

**Issue by algpet** [etherdelta/etherdelta.github.io#469]
I can't place orders ( buy or sell ) with python etherdelta API. I tried two different API implementations , and I always stuck there. I have funds at my wallet. I have enough funds deposited to smart contract. I even hold few OMG tokens at smartcontract in case I do something wrong with side of trade. Yet nothing. Anyone is having same issue ? anyone was able to pass through it ? any non-python successes ?

**Comment by algpet** [comment]
solved myself

**Comment by marcoalkema** [comment]
What was your fix? I'm facing this same issue...

**Comment by GoldRat** [comment]
The same on C#. What is wrong with this message?
`42["message", {"amountGive":878460000000000,"tokenGive":"0x0000000000000000000000000000000000000000","amountGet":60000000000000000,"tokenGet":"0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a","contractAddr":"0x8d12a197cb00d4747a1fe03395095ce2a5cc6819","expires":6847936,"nonce":1625988488,"user":"0x826d9762eac3f3cda77296f71f1cd077701a8009","v":27,"r":"0xe47d86cdcfe122f50b8a712f7433b7e5988b17bcfa847d437140c0f47fc8adf4","s":"0x17c69abbae042122ceba191897800e823ab5b88963b4faa4514cde6aa53ec15c"}]`

**Comment by algpet** [comment]
This was quite a few ago. But as long as I remember that was just a stupid issue. For some reason
version of python I used to use produced "r" and "s" signature parameters not as hex (but rather as integers or strings). So I had to r=hex(r) s=hex(s) myself.
But as long as I see goldrat's message contain it right , so it should be other issue that I had originally , when I posted that issue at github.

**Comment by GoldRat** [comment]
So it seems that the reason is wrong signature but not "because available volume too low" as Zack examples are trying to tell us. And these bot examples make wrong signature. I'll try to sign myself. Thanks.

**Comment by algpet** [comment]
yes , I can confirm that this had nothing to do with available volume for me.
