### ISSUE TITLE
[macOS - Safari/Firefox] Site makes the browser window unresponsive on load

### ISSUE THREAD

**Issue by crutor0x** [etherdelta/etherdelta.github.io#47]
Yesterday I discovered EtherDelta and was checking it out in Safari, everything worked fine. I wanted to try it out so I installed MetaMask on Chrome and played with it for a while, just to see how the site works etc. Later that day I was back in Safari (Chrome and MetaMask were closed) and wanted to just check the orders/graphs on some tokens, but I couldn't get the site to work.

It loaded the basic DOM interface, but when it started to load the content (tokens, orders and basically everything) the site froze. Not only the site, but the entire tab it was open in. I couldn't refresh it, I couldn't go to a different website, I could only close the current tab to make Safari responding again.

I tried to open it in Firefox but it was the same as in Safari. Only browser that now works is Chrome with MetaMask installed (haven't yet tried it without MetaMask).
It kinda sucks for me because Safari is my main browser and I use Chrome/MetaMask only when I want to trade there. So when  I just want to check the current prices and whatnot, I still have to open Chrome because it just won't load elsewhere.

The site always freezes when it starts loading all the stuff from the database and was working fine before I opened an account there using Chrome/MetaMask. I don't know how the site uses the local storage, but is it possible that the site is trying to connect to my MetaMask account even when I'm in different browser without MetaMask, causing the site to freeze?

**Comment by 1337cookie** [comment]
I think one of the bigger issues here is that not all browsers use the same javascript engine so when you get an application that is built on a variety of different javascript packages and code libraries, you start to run into issues with the consistency of code being executed.  EtherDelta is built on the Node JS ecosystem which is built specifically on Chrome's Javascript engine.

**Comment by crutor0x** [comment]
Nevermind, it started working again today, weird...

@1337cookie Doesn't both Safari and Chrome use Webkit?
