### ISSUE TITLE
Show a note/warning about ethereum transactions

### ISSUE THREAD

**Issue by pedddro** [etherdelta/etherdelta.github.io#51]
I think there should be a warning or a note about the necessity of having ether in order to pay for transactions involving depositing, withdrawing, and trading.

**Comment by 1337cookie** [comment]
I think you should read the guides before attempting to use a service that has no warranty, no sign up process and is based on technology that is essentially in open beta.

**Comment by pedddro** [comment]
I think this is still valid @zackcoburn zackcoburn update

**Comment by pedddro** [comment]
I think this is still valid @zackcoburn, we should never blame the user. As the ethereum transaction costs only 0.1 gwei, this would avoid a lot of stuck funds.
