### ISSUE TITLE
No response from API on "message"(New Order).

### ISSUE THREAD

**Issue by burja8x** [etherdelta/etherdelta.github.io#513]
I am using C# WebSocket4Net.WebSocket.
Connection works fine. I got trades, orders, funds,...
GetMarket and Ping works fine.
But, when I am trying to Send new order ("message"), I dont get response from Api.
![image](https://user-images.githubusercontent.com/23376226/37875299-0eef3386-303d-11e8-8f69-5e2d6436ed17.png)

**Comment by burja8x** [comment]
It was wrong json format. My mistake.

**Comment by GoldRat** [comment]
Hello. Could you give an example how to send new order ("message") using C# WebSocket4Net.WebSocket, please?
