### ISSUE TITLE
Open Trades not live updated

### ISSUE THREAD

**Issue by Texxer** [etherdelta/etherdelta.github.io#94]
"You cannot trade this order because it already traded. Someone else already traded this order and the order book hasn't updated yet."

"You tried to send an Ethereum transaction but there was an error."

Trading is impossible.

- is the developer fixing this?

**Comment by zackcoburn** [comment]
> **Increased network activity:**

> There are >5,000 pending Ethereum transactions (due to a recent flurry of activity on the Ethereum network).

> If you’re having trouble getting transactions through, this is definitely why.

> Expect transactions to be delayed for hours, or dropped entirely (for deposits, withdrawals, and trades).

> Don't be surprised if the "pending time" shown on Etherscan resets, or if the transaction just disappears entirely.

> This backlog could take many hours for the Ethereum network to process.

> Track the number of pending transactions here: https://etherscan.io/txsPending

> If you'd like, you can increase your gas price to increase transaction speed. See the "gas price" option in the upper right dropdown.

> If you aren't using MetaMask, then you are sending your transactions through the Etherscan API. There are reports that Etherscan API is having trouble broadcasting transactions today. This would explain the "You tried to send an Ethereum transaction but there was an error" message you may be seeing. Sometimes refreshing and trying again will fix it, sometimes you have to wait for your pending transactions to confirm first. To see your pending transactions, go to https://etherscan.io and enter your address. The greyed out transactions are pending.
